Set s = CreateObject("Wscript.Shell")
do
wscript.sleep 80
s.sendkeys"{esc}"
wscript.sleep 80
s.sendkeys"{capslock}"
wscript.sleep 80
s.sendkeys"{scrolllock}"
wscript.sleep 80

wscript.sleep 80
s.sendkeys"{esc}"
wscript.sleep 80
s.sendkeys"{capslock}"
wscript.sleep 80
s.sendkeys"{scrolllock}"
wscript.sleep 80

s.sendkeys"{scrolllock}"
wscript.sleep 80
s.sendkeys"{capslock}"
wscript.sleep 80
s.sendkeys"{esc}"
wscript.sleep 80

wscript.sleep 80
s.sendkeys"{scrolllock}"
wscript.sleep 80
s.sendkeys"{capslock}"
wscript.sleep 80
s.sendkeys"{esc}"
wscript.sleep 80
s.sendkeys"{esc}"
wscript.sleep 80
s.sendkeys"{capslock}"
wscript.sleep 80
s.sendkeys"{scrolllock}"
wscript.sleep 80
loop